# Config for Dependabot updates. See Documentation here:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:

  # Enable version updates for Docker Compose
  - package-ecosystem: 'docker-compose'
    # Look for a `Dockerfile` in the `compose/local/docs` directory
    directory: '/'
    # Every month
    schedule:
      interval: 'monthly'

  